apiVersion: apps/v1
kind: Deployment
metadata:
  name: prpo-history-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prpo-history
  template:
    metadata:
      labels:
        app: prpo-history
    spec:
      containers:
      - image: janezju/prpo-room-history
        name: prpo-history
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: prpo-history
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      name: server
      protocol: TCP
  selector:
    app: prpo-history
